### ISSUE TITLE
[Feature] Add html anchor support

### ISSUE THREAD

**Issue by igor-tsiglyar** [theoludwig/markdownlint-rule-relative-links#4]
## Description

It seems that currently only links to markdown headers are processed, unlike https://github.com/DavidAnson/markdownlint/blob/main/doc/md051.md which also supports links to html anchors.

## Describe the solution you'd like

Would be great to have the same processing logic as md051 so that this plugin is usable with anchors.

## Describe alternatives you've considered

Current workaround is using https://github.com/tcort/markdown-link-check with the following config:

```
{
    "ignorePatterns": [
      {
        "pattern": "^#"
      }
    ]
}
```

This utility also does not work well with anchors so we can ignore all the links to them while links to files are being verified just fine.

**Comment by theoludwig** [comment]
Hello! @igor-tsiglyar :wave:

Thanks for opening this feature request.

> It seems that currently only links to markdown headers are processed

Yes, this is the case since the v2 of this custom rule (related: #2), before it was only checking if the files exists and ignoring everything anchors related.
If I remember correctly, when this have been added, it was the same behavior/implementation of markdownlint, and since then, the implementation changed to add more cases other than only headings anchors.

> Would be great to have the same processing logic as md051 so that this plugin is usable with anchors.

Definitely, I agree!
Would be much appreciated if someone could open a PR to implement this feature.
The implementation inside `markdownlint` is here: https://github.com/DavidAnson/markdownlint/blob/main/lib/md051.js and we should certainly take inspiration from there.

A PR for a failing test case would already be a good contribution. :smile:
I refactored the tests so it's easier to add new test cases.
Also the README have been updated to describe the current features and limitations of the rule.
